### DISCUSSION TITLE
/traefik-v2-and-unifi-controller-in-docker/

### DISCUSSION THREAD

**Discussion by migratecomments** [ironicbadger/blog.ktz.me#139] [Announcements]
Traefik v2 and Unifi Controller in docker
        
[https://blog.ktz.me/traefik-v2-and-unifi-controller-in-docker/](https://blog.ktz.me/traefik-v2-and-unifi-controller-in-docker/)

**Comment by migratecomments** [comment]
```header
Originally posted by d3wy on 2020-09-24 00:03
```

Alex, do you use the Android or iOS Unifi apps? Are you able to connect to your controller with this url generated by Traefik?

**Reply by migratecomments** [reply]
```header
Originally posted on 2020-09-24 05:56
```

Yes and yes

**Comment by migratecomments** [comment]
```header
Originally posted by DonS from NZ on 2021-01-24 23:06
```

Hi Alex, self hosted SRE here. Have you seen the latest YT vid from Laurence Systems, UniFi Alternatives? Is Ubiquity moving to a cloud Locked controller software. That would be a great shame. I think they are losing their way. BTW I got 3 of those HP290s before they went OOS, Love what you do. Best Regards Don

**Comment by migratecomments** [comment]
```header
Originally posted by mikensan on 2021-01-25 16:50
```

Ah thanks! the skipverify solved my problem (internal server error), was driving me up the wall!

**Comment by migratecomments** [comment]
```header
Originally posted by Elias Pereira on 2021-08-03 09:09
```

Hello,

Do you know if there is any way to configure the following command:

`serversTransport:   insecureSkipVerify: true   `

only on the service in question?

I ask this because I set it globally and it affected other docker services I own.

**Reply by migratecomments** [reply]
```header
Originally posted on 2021-08-03 09:21
```

Yes, I think you might be able to:-

\- [https://doc.traefik.io/trae...](https://doc.traefik.io/traefik/v2.4/routing/services/#serverstransport)

The docs state you can create a dynamic configuration service referencing a specific serversTransport configuration.

edit: further digging and it's not as easy I'd hoped. I've opened a Github issue to track this question with Traefik.

[https://github.com/traefik/...](https://github.com/traefik/traefik/issues/8327)

**Reply by migratecomments** [reply]
```header
Originally posted by Elias Pereira on 2021-08-04 05:56
```

The issue was closed and your question was not answered.

As far as I noticed, only global is possible.

**Comment by migratecomments** [comment]
```header
Originally posted by Oncleben31 on 2021-08-21 09:22
```

Thank you for sharing. Direct answer for the issued I got 5 minutes ago.

**Comment by migratecomments** [comment]
```header
Originally posted by James Newman on 2021-10-15 20:27
```

Thank you for sharing all of this. I am coming from the TechnoTim - Put SSL on everything with Traefik and Lets Encrypt tutorial. I have all my apps runnng well behind Traefik and SSL. Of course Unifi is the only one that is giving me problems. I have tried incorporating you solution within his framework but its not working. Any chance you are familiar with his framework? Any advice is greatly appreciated!

Thanks,  
James

**Reply by kyleinprogress** [reply]
If James sees this, here's how I combined Alex's fixes with Tim's to get Unifi working:

```
  unifi:
    image: ghcr.io/linuxserver/unifi-controller
    container_name: unifi
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - 8080:8080
      - 3478:3478/udp
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/appdata/unifi:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.unifi.entrypoints=http"
      - "traefik.http.routers.unifi.rule=Host(`unifi.local.example.com`)"
      - "traefik.http.middlewares.unifi-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.unifi.middlewares=portainer-https-redirect"
      - "traefik.http.routers.unifi-secure.entrypoints=https"
      - "traefik.http.routers.unifi-secure.rule=Host(`unifi.local.example.com`)"
      - "traefik.http.routers.unifi-secure.tls=true"
      - "traefik.http.routers.unifi-secure.service=unifi"
      - "traefik.http.services.unifi.loadbalancer.server.port=8443"
      - "traefik.http.services.unifi.loadbalancer.server.scheme=https"
      - "traefik.docker.network=proxy"
 ```
One thing to note for anyone who finds this in the future. If you decide to use traefik and put unifi on a different machine (ip) than traefik, you'll need to set your inform host override in the controller to the IP of the actual machine unifi is running on. So if you have traefik running on 10.0.0.10 and proxying to a pi with unifi on 10.0.0.20, the domain will point to the wrong IP. So you need to either setup a specific domain name for just inform IP or just change the inform host to the IP of the pi running Unifi (10.0.0.20).

If the host name you setup resolves to the same IP that port 8080 is on, then you don't have to do anything.
