### DISCUSSION TITLE
/configure-traefik-macvlans-synology/

### DISCUSSION THREAD

**Discussion by migratecomments** [ironicbadger/blog.ktz.me#211] [Announcements]
Configuring Traefik on Synology DSM7 using docker macvlans
        
[https://blog.ktz.me/configure-traefik-macvlans-synology/](https://blog.ktz.me/configure-traefik-macvlans-synology/)

**Comment by ghost** [comment]
Hello Alex,

Thank you for this post, i have a question (I'm still learning all of this). I see that i need to use macvlan's for Traefik on my Synology but how would i put PiHole behind Traefik as well? Do i need to make another macvlan for PiHole? I've read some little bits of routing the admin panel to Traefik but letting everything else pass through normally?

Again, I'm still learning and don't know what the best approach for this would be or how to get it configured the right way. I would appreciate it if you have a step by step plan to set this up as well or if you can point me in the right direction if you're willing and have the time.

Thanks.

**Comment by Joker2015** [comment]
Hi Alex,

thanks for the post - I've been struggeling with traefik for weeks (and no solution so far). However, I got two questions

- why do I need to create the macvlan on os level? I watched the video by networkchuck and I dod not see that step there. Is this a synology thing?
- in your script you use these lines

```
ip addr add 192.168.4.204/30 dev macvlan0
ip link set macvlan0 up
ip route add 192.168.44.204/30 dev macvlan0
```

there is 192.168.**4**.204 and 192.168.**44**.204. I think that this is a typo, but as it is not working in my environment, I'm not 100% sure :-(
best regards - Achim

**Reply by ironicbadger** [reply]
You are right. All the `192.168.4.x` should be `44`.

**Comment by bartclone** [comment]
Brilliant, Alex.
No need however, for a separate script and chmodding that.
You can easily put the script inside the task, and set that to run at startup.

**Reply by bartclone** [reply]
> Brilliant, Alex.
> No need however, for a separate script and chmodding that.
> You can easily put the script inside the task, and set that to run at startup.

I did some testing; turns out that the bridge itself doesn’t need an IP per se, so:

```ip addr add 192.168.44.204/30 dev macvlan0 ```
and
```ip route add 192.168.44.204/30 dev macvlan0 ```
can be left out.

Anyone that can confirm?

**Reply by ironicbadger** [reply]
Interesting! It's been a while since I loaded this into my context buffer so I don't recall the details but if you say it is so, it is so.

**Comment by rtmlp** [comment]
Hi. Thanks a lot for both the articles on `macvlan` and `traefik` for synology. While running the following commands 

```
ip addr add 192.168.4.204/30 dev macvlan0
ip link set macvlan0 up
ip route add 192.168.44.204/30 dev macvlan0
```

I get the following error `RTNETLINK answers: File exists` for the last command. Do you have any idea about this error ?

**Reply by bartclone** [reply]
That's because these commands introduce a second gateway. 
Not needed.
Try with only ```ip link set macvlan0 up```

(So, leave out ```ip addr add``` and ```ip route add``` )

**Reply by rtmlp** [reply]
I tried doing that. However, I got another error 

```ERROR: for a4de34c1be47_traefik  Cannot start service traefik: Invalid address 10.20.100.201: It does not belong to any of this network's subnets```

This is what I have changed

```
ip link add macvlan0 link ovs_eth0 type macvlan mode bridge
# and then went to 
docker-compose up -d
```

**Reply by rtmlp** [reply]
The network settings in the `yml` file is 
```

networks:
  frontend:
    external: true
  macvlan:
    name: macvlan
    driver: macvlan
    driver_opts:
      parent: ovs_eth0
    ipam:
      config:
        - subnet: 10.20.10.0/24
          ip_range: 10.20.10.200/29
          gateway: 10.20.10.1
```

and I have provided the following network settings for `tr` container 

```
    networks:
      macvlan:
        ipv4_address: 10.20.100.201
      frontend:
    restart: unless-stopped
```

**Reply by rtmlp** [reply]
Oh god. I should have done `ipv4_address: 10.20.10.200` instead of `ipv4_address: 10.20.100.201`. Updated and it created

**Reply by rtmlp** [reply]
Few questions that I have while trying to debug

1. It seems like all my containers are created under different network `172.18.0.*`. Is that correct behavior? Pic attached [here](https://ibb.co/ZKmF23X)
2. Do I have create any files in the `/volume1/docker/traefik/config` location. Right now it is empty. Should it have `acme.json`, `traefik.yml` etc ?
3. When I open `traefik.domain.com` now (with my own domain and `A` record with wildcard `*` in cloudfare pointing to `10.20.10.200`), I just get `404 page not found` 

Can anyone help in this ?

**Reply by bartclone** [reply]
1. No issue. You should however be able to access (ping) 10.20.100.201 (=traefik) on your local network
2. Cant guess what’s in your docker-compose.yml
3. Why do you put in a local 10.x IP at Cloudflare - that’s not your external IP?!

**Reply by bartclone** [reply]
Oh, and on your router, portforward ports 80/443 to your Traefik instance/IP

**Comment by olaf-lexemo** [comment]
When I try to start traefik, I always get:
`Error response from daemon: driver failed programming external connectivity on endpoint traefik (f584c21b956ec90f5e21cc4c768a21b681ab6add3b71bb2f05d3c3e15b29917c): Error starting userland proxy: listen tcp4 0.0.0.0:443: bind: address already in use`
I also have a pi-hole container running on 192.168.23.24, which is working just fine. that's configured using the DSM Docker UI though but it's using the macvlan and frontend networks too. but even before I moved that container into the 24/30 network range I always got the very same error message.
only difference now is that DSM is not forcing a redirection from the .24:80 to .24:5000 all the time. When trying to use the .24 for traefik at `ipv4_address`, I got the exact same error.

`ovs_eth4` is associated with my 1-GbE Nic in the Synology.

any suggestions?

in the docker-compose.yml under traefik I have:
```yaml
    networks:
      macvlan0:
        ipv4_address: 192.168.23.25
      frontend:
```

and at the end of the file:
```yaml
networks:
  frontend:
    external: true
  macvlan:
    name: macvlan0
    driver: macvlan
    driver_opts:
      parent: ovs_eth4
    ipam:
      config:
        - subnet: 192.168.23.0/24
          ip_range: 192.168.23.24/30
          gateway: 192.168.23.1
```
