### DISCUSSION TITLE
use-1-pikvm-instance-to-control-4-systems/

### DISCUSSION THREAD

**Discussion by giscus** [ironicbadger/blog.ktz.me#219] [Announcements]
# use-1-pikvm-instance-to-control-4-systems/

And there we have it. One PiKVM able to control and view up to 4 systems at once. And with the addition of a USB thumb drive to the KVM we can even boot any ISO we want!

https://blog.ktz.me/use-1-pikvm-instance-to-control-4-systems/

**Comment by timothystewart6** [comment]
Great post!  It's such a great setup!  Thanks for the mention!

**Reply by veteranbv** [reply]
It was seriously a great video and I implemented it in my homelab as well!

**Comment by t3kg33k** [comment]
Great post. Coincidentally, I was actually looking at setting of a PiKVM for my home servers. You've motivated me more.

**Comment by veteranbv** [comment]
Love this. Recently used Tim’s video to do something similar! What did you use to draw the connection diagram above? Awesome work!

**Comment by padraic7a** [comment]
So the pi, loaded with pikvm sits in front of the hardware kvm?

I wonder if that woukd work with any physical kvm switch? Ali has one here for a very reasonable looking price
https://a.aliexpress.com/_mKx4ktw

**Comment by keatre** [comment]
Trying to understand the Pi USB-C to the KVM with the power splitter.  Theoretically, you could power the pi with a PoE hat, and then go from USB-C to KVM, right? Or from the pi USB-A to KVM? Speaking only about the yellow line in the diagram, not the red.

**Comment by homonto** [comment]
I just did the same with cheap 40$ kvm switch (4x hdmi and usb) from Ali ;-)

**Reply by ngysling** [reply]
Which one did you use? I've seen those on Aliexpress but I thought that there was surely a catch. This is the one I found https://www.aliexpress.us/item/3256805012764711

**Reply by ngysling** [reply]
ah shoot dead link, it was a 4k 60hz hdmi 2.0 kvm with 4 outputs for $38.

**Reply by homonto** [reply]
https://www.aliexpress.com/item/1005004725859381.html

**Reply by ngysling** [reply]
awesome, thank you. the splitter and csi bridge are also available on ALI for significantly cheaper. with coupons i'm all in for $72.

**Reply by ngysling** [reply]
Just got mine in the mail, haven't gotten the chance to set it up but will in a few days. From what I can see, is the USB-C port on the right front side labelled "Select" where the USB input switching happens?

**Reply by homonto** [reply]
I bought 2 already and probably will go for 1 more. switching is perfect with pikvm diy v2 
however some of my devices - i.e. firewall - does not synchronize properly if, DURING THE REBOOT the kvm is NOT connected to it

**Reply by ngysling** [reply]
And the config side is the exact same i.e using ezcoo drivers in the override.yaml?

**Reply by homonto** [reply]
?

**Reply by ngysling** [reply]
I'm asking if you use the same code as used in this writeup and the PiKVM wiki for the EzCoo switch, found here. 
https://docs.pikvm.org/ezcoo/

**Reply by homonto** [reply]
I used all standard settings on pikvm itself
of course modyfing only the ip, wifi etc
so not the ezcoo setting but let say vanilla ones

**Reply by ngysling** [reply]
Vanilla ones hmm. So no changes to the yaml config files? Are you able to control the input switching from the PiKVM interface? I got it setup and the button switching works ofc but I still have yet to dabble with the software. 

Sorry if I'm burdening you with questions, I just want to figure this out as a budget alternative to the EzCoo. The  KC-KVM401A clearly has a remote input feature through the included infrared reader, I just have no idea how I could copy whatever data it's sending to simulate it.

**Reply by abonforti** [reply]
@hogcycle have you been able to figure out so?

**Comment by homonto** [comment]
```
cat /etc/kvmd/override.yaml
kvmd:
    gpio:
        drivers:
            reboot:
                type: cmd
                cmd: [/usr/bin/sudo, reboot]
            restart_service:
                type: cmd
                cmd: [/usr/bin/sudo, systemctl, restart, kvmd]
        scheme:
            button1:
                pin: 26
                mode: output
                switch: false
            button2:
                pin: 19
                mode: output
                switch: false
            button3:
                pin: 13 
                mode: output
                switch: false 
            button4:
                pin: 6
                mode: output
                switch: false
            reboot_button:
                driver: reboot
                pin: 0
                mode: output
                switch: false
            restart_service_button:
                driver: restart_service
                pin: 0
                mode: output
                switch: false
        view:
            header:
                title: Sources  # The menu title
            table: 
                #- ["#1-TrueNAS:", ch1_led, button1]
                - ["#1-TrueNAS:", button1]
                - ["#2-monkey:", button2]
                - ["#3-sabaj:", button3]  
                - ["#4-firewall:", button4]
                - ["#PiKVM", "restart_service_button|confirm|Restart kmvd", "reboot_button|confirm|Reboot"]
```
<img width="314" alt="Screenshot 2024-03-29 at 11 12 08" src="https://github.com/ironicbadger/blog.ktz.me/assets/46562447/6a2f1001-64ef-4034-9420-85254ebc8a9e">
